listagem = ("Pão", 1.8, "Frango", 10.6, "Lapis", 2.0, "Açucar", 20)
print("—"*30)
print(f"{listagem[0]}.........................R$: {listagem[1]}")
print(f"{listagem[2]}.......................R$: {listagem[3]}")
print(f"{listagem[4]}.........................R$: {listagem[5]}")
print(f"{listagem[6]}.........................R$: {listagem[7]}\n")
